Repository wecode-bootcamp-korea/14-1st-StyleCode-frontend, pull requests merged in 2020-11, with the labels that each got.

#2 [14기 엄문주] Login page
  package-lock.json
  package.json
  public/data/birthday.json
  public/data/init.txt
  public/data/productdetail.json
  public/images/facebook.png
  public/images/facebookinformation.png
  public/images/google.png
  public/images/init.txt
  public/images/kakao.png
  public/images/loginbackground.jpg
  public/images/mainlogo.png
  public/images/testImageInProductdetail.jpeg
  public/images/twitter.png
  src/Component/Login/Login.js
  src/Component/Login/Login.scss
  src/Component/Login/images/00-blank.html
  src/Component/Login/images/loginbackground.jpg
  src/Routes.js
  src/Styles/reset.scss
  src/index.js
  test.js
Labels: Status: 리뷰 요청

#3 [14기 박현재] Add: ootd's main page
  package-lock.json
  package.json
  public/data/data.json
  src/Common/Navbar/NavbarOotd/NavbarOotd.js
  src/Common/Navbar/NavbarOotd/NavbarOotd.scss
  src/Common/Navbar/NavbarStore/NavbarStore.js
  src/Common/Navbar/NavbarStore/NavbarStore.scss
  src/Pages/Ootd/Components/MenuTab.js
  src/Pages/Ootd/Main/Card.js
  src/Pages/Ootd/Main/Card.scss
  src/Pages/Ootd/Main/CardList.js
  src/Pages/Ootd/Main/CardList.scss
  src/Pages/Ootd/Main/Main.js
  src/Pages/Ootd/Main/Main.scss
  src/Pages/Ootd/Ootd.js
  src/Pages/Ootd/images/navLogo.png
  src/Routes.js
Labels: Status: 컨플릭트 해결 요청

#5 [14기 박현재] Add: navbar
  src/Common/Navbar/NavbarOotd/NavbarOotd.js
  src/Common/Navbar/NavbarOotd/NavbarOotd.scss
  src/Common/Navbar/NavbarStore/NavbarStore.js
  src/Common/Navbar/NavbarStore/NavbarStore.scss
  src/Routes.js
Labels: Status: 리뷰 요청

#4 [14기 엄문주] SignUp page
  public/data/agree.json
  public/images/femaleicon.png
  public/images/maleicon.png
  src/Component/SignUp/SignUp.js
  src/Component/SignUp/SignUp.scss
  src/Routes.js
  src/config.js
  src/index.js
Labels: Status: 리뷰 요청

#10 [14기 장호철] README 업데이트
  README.md
Labels: Status: 리뷰 요청

#6 [14기 엄문주] Productdetail page
  package-lock.json
  package.json
  public/data/option.json
  src/Component/ProductDetail/Component/Article/ProductInfo/ProductInfo.js
  src/Component/ProductDetail/Component/Article/ProductReview/Component/SampleNextArrow.js
  src/Component/ProductDetail/Component/Article/ProductReview/Component/SamplePrevArrow.js
  src/Component/ProductDetail/Component/Article/ProductReview/ProductReview.js
  src/Component/ProductDetail/Component/Article/ProductReviewImgbox/ProductReviewImgbox.js
  src/Component/ProductDetail/Component/Header/Header.js
  src/Component/ProductDetail/Component/Header/Orderbox/Orderbox.js
  src/Component/ProductDetail/Component/Header/Orderbox/Orderbox.scss
  src/Component/ProductDetail/Component/Header/Orderbox/Orderbox2.js
  src/Component/ProductDetail/Component/Header/Orderbox/Orderbox2.scss
  src/Component/ProductDetail/Component/Header/Select/Select.js
  src/Component/ProductDetail/ProductDetail.js
  src/Component/ProductDetail/ProductDetail.scss
  src/Routes.js
Labels: Status: 리뷰 요청

#8 [14기 장호철] 카테고리 디테일 페이지
  package-lock.json
  package.json
  public/data/categoryDetailJumbotron.json
  public/data/mdChoiceItem.json
  public/data/showAllItem.json
  public/data/sidebarCategoryList.json
  public/images/categoryDetail/jumbotron/jumbotron0.jpg
  public/images/categoryDetail/jumbotron/jumbotron1.jpg
  public/images/categoryDetail/jumbotron/jumbotron2.jpg
  public/images/categoryDetail/jumbotron/jumbotron3.jpg
  public/images/categoryDetail/jumbotron/jumbotron4.jpg
  public/images/categoryDetail/jumbotron/jumbotron5.jpg
  public/images/categoryDetail/jumbotron/jumbotron6.jpg
  public/images/categoryDetail/jumbotron/jumbotron7.jpg
  public/images/categoryDetail/jumbotron/jumbotron8.jpg
  public/images/categoryDetail/jumbotron/jumbotron9.jpg
  public/images/categoryDetail/jumbotron/model2.jpg
  public/images/categoryDetail/jumbotron/model3.jpg
  public/images/categoryDetail/mdChoice/popularProduct0.jpg
  public/images/categoryDetail/mdChoice/popularProduct1.jpg
  public/images/categoryDetail/mdChoice/popularProduct2.jpg
  public/images/categoryDetail/mdChoice/popularProduct3.jpg
  public/images/icon/arrow.png
  public/images/icon/filterArrow.png
  public/images/icon/filterDropDownArrow.png
  src/Component/CategoryDetail/CategoryDetail.js
  src/Component/CategoryDetail/CategoryDetail.scss
  src/Component/CategoryDetail/Component/Asidebar/Asidebar.js
  src/Component/CategoryDetail/Component/Asidebar/Asidebar.scss
  src/Component/CategoryDetail/Component/Jumbotron/Jumbotron.js
  src/Component/CategoryDetail/Component/Jumbotron/Jumbotron.scss
  src/Component/CategoryDetail/Component/MdChoice/MdChoice.js
  src/Component/CategoryDetail/Component/MdChoice/MdChoice.scss
  src/Component/CategoryDetail/Component/MdChoice/Pagination.js
  src/Component/CategoryDetail/Component/MdChoice/Pagination.scss
  src/Component/CategoryDetail/Component/ShowAll/ShowAll.js
  src/Component/CategoryDetail/Component/ShowAll/ShowAll.scss
  src/Routes.js
  src/config.js
Labels: Status: 리뷰 요청

#9 [14기 장호철] 검색 결과 페이지
  public/data/searchProductItem.json
  public/images/search/fake.png
  public/images/search/fakeLogo.png
  public/images/search/femaleIcon.png
  public/images/search/maleIcon.png
  public/images/search/marketingItem.jpg
  public/images/search/marketingItem2.jpg
  public/images/search/nikeLogo.jpg
  src/Component/Search/Component/Product/Product.js
  src/Component/Search/Component/Product/Product.scss
  src/Component/Search/Component/User/User.js
  src/Component/Search/Component/User/User.scss
  src/Component/Search/Search.js
  src/Component/Search/Search.scss
  src/Component/SearchPage/SearchPage.js
  src/Component/SearchPage/SearchPage.scss
  src/config.js
Labels: Status: 컨플릭트 해결 요청

#12 [14기 엄문주] 로그인페이지
  src/Component/Login/Login.js
  src/Component/Login/Login.scss
Labels: Status: 리뷰 요청

#16 [14기 장호철] 스토어 메인페이지 리팩토링
  public/data/brandItem.json
  public/data/popularProduct.json
  src/Component/Cart/Cart.js
  src/Component/Cart/Cart.scss
  src/Component/Cart/Component/Footer/CartFooter.scss
  src/Pages/Store/Home/Component/Footer/Footer.js
  src/Pages/Store/Home/Component/Footer/Footer.scss
  src/Pages/Store/Home/Component/PopularBrand/PopularBrand.js
  src/Pages/Store/Home/Component/PopularBrand/PopularBrand.scss
  src/Pages/Store/Home/Component/PopularProduct/Component/All.js
  src/Pages/Store/Home/Component/PopularProduct/Component/Card.scss
  src/Pages/Store/Home/Component/PopularProduct/PopularProduct.scss
  src/Pages/Store/Home/Component/StoreMainJumbotron/StoreMainJumbotron.js
  src/Pages/Store/Home/Component/StoreMainJumbotron/StoreMainJumbotron.scss
  src/Pages/Store/Home/Component/Trend/Trend.js
  src/Pages/Store/Home/Home.js
  src/Pages/Store/Home/Home.scss
  src/Pages/Store/Unisex/Component/ShowAll/ShowAll.js
  src/Pages/Store/Unisex/Component/ShowAll/ShowAll.scss
  src/Pages/Store/Unisex/Component/Sidebar/Sidebar.js
  src/Pages/Store/Unisex/Component/Sidebar/Sidebar.scss
  src/Pages/Store/Unisex/Unisex.js
  src/Pages/Store/Unisex/Unisex.scss
Labels: Status: 리뷰 요청

#15 [14기 장호철] 카테고리 페이지 리팩토링
  src/Component/CategoryDetail/CategoryDetail.js
  src/Component/CategoryDetail/Component/CategoryJumbotron/CategoryJumbotron.js
  src/Component/CategoryDetail/Component/CategoryJumbotron/CategoryJumbotron.scss
  src/Component/CategoryDetail/Component/MdChoice/MdChoice.js
  src/Component/CategoryDetail/Component/ShowAll/ShowAll.js
  src/config.js
Labels: Status: 리뷰 요청

#17 [14기 장호철] 검색결과 페이지 리팩토링
  src/Component/Search/Search.js
  src/Component/Search/Search.scss
Labels: Status: 리뷰 요청

#18 [14기 장호철] 장바구니 페이지 리팩토링
  src/Component/Cart/Cart.js
  src/Component/Cart/Component/Asidebar/FillAsidebar.js
  src/Component/Cart/Component/EmptyTable/EmptyTable.js
  src/Component/Cart/Component/ProductTable/ProductTable.js
  src/config.js
Labels: Status: Accepted

#24 [14기 장호철] 카테고리 페이지 CSS 수정
  src/Component/CategoryDetail/CategoryDetail.js
  src/Component/CategoryDetail/CategoryDetail.scss
  src/Component/CategoryDetail/Component/Asidebar/Asidebar.js
  src/Component/CategoryDetail/Component/Asidebar/Asidebar.scss
  src/Component/CategoryDetail/Component/MdChoice/MdChoice.js
  src/Component/CategoryDetail/Component/MdChoice/MdChoice.scss
  src/Component/CategoryDetail/Component/MdChoice/Pagination.js
  src/Component/CategoryDetail/Component/MdChoice/Pagination.scss
  src/Component/CategoryDetail/Component/ShowAll/ShowAll.js
  src/Component/ProductDetail/Component/Header/Select/Select.js
  src/Component/ProductDetail/ProductDetail.js
  src/config.js
Labels: Status: 리뷰 요청

#23 [14기 박현재] Add: Navbar Search Function
  src/Component/Cart/Cart.js
  src/Component/CategoryDetail/CategoryDetail.js
  src/Component/Navbar/NavbarOotd/NavbarOotd.js
  src/Component/Navbar/NavbarOotd/NavbarOotd.scss
  src/Component/Navbar/NavbarStore/NavbarBeforeSignIn.js
  src/Component/Navbar/NavbarStore/NavbarBeforeSignIn.scss
  src/Component/Navbar/NavbarStore/NavbarStore.js
  src/Component/Navbar/NavbarStore/NavbarStore.scss
  src/Component/Search/Search.js
  src/Pages/Ootd/Main/Main.js
  src/Pages/Store/Home/Home.js
Labels: Status: 리뷰 요청

#21 [14기 엄문주] 상품 상세 페이지 입니다.
  public/data/productdetailsample.json
  public/images/coupon.png
  src/Component/ProductDetail/Component/Article/ProductInfo/ProductInfo.js
  src/Component/ProductDetail/Component/Article/ProductReviewImgbox/ProductReviewImgbox.js
  src/Component/ProductDetail/Component/Header/Header.js
  src/Component/ProductDetail/Component/Header/Select/Select.js
  src/Component/ProductDetail/ProductDetail.js
  src/Component/ProductDetail/ProductDetail.scss
Labels: Status: 리뷰 요청

#19 [14기 엄문주] 회원가입 페이지
  public/data/birthday.json
  src/Component/SignUp/SignUp.js
  src/Component/SignUp/SignUp.scss
Labels: Status: 리뷰 요청

#20 [14기 장호철] 메인페이지 인기상품 메뉴탭 구현 !
  public/data/popularProduct.json
  public/images/product/unisex3.jpg
  src/Pages/Store/Home/Component/PopularProduct/Component/All.js
  src/Pages/Store/Home/Component/PopularProduct/Component/BagEtc.js
  src/Pages/Store/Home/Component/PopularProduct/Component/Beauty.js
  src/Pages/Store/Home/Component/PopularProduct/Component/Female.js
  src/Pages/Store/Home/Component/PopularProduct/Component/Life.js
  src/Pages/Store/Home/Component/PopularProduct/Component/Shoes.js
  src/Pages/Store/Home/Component/PopularProduct/Component/Tech.js
  src/Pages/Store/Home/Component/PopularProduct/Component/Unisex.js
  src/Pages/Store/Home/Component/PopularProduct/PopularProduct.js
Labels: Status: 리뷰 요청

#22 [14기 장호철] 검색페이지 config 수정
  src/Component/Search/Search.scss
  src/config.js
Labels: Status: 컨플릭트 해결 요청

#25 [14기 장호철] 디테일 페이지 리팩토링
  src/Component/Cart/Cart.js
  src/Component/Cart/Cart.scss
  src/Component/Cart/Component/Asidebar/FillAsidebar.js
  src/Component/Cart/Component/ProductTable/ProductTable.js
  src/Component/Login/Login.js
  src/Component/SignUp/SignUp.js
Labels: Status: 리뷰 요청

#13 [14기 박현재] Add: OOTD create modal & update main
  package-lock.json
  package.json
  public/data/data.json
  public/index.html
  src/Pages/Ootd/Components/MenuTab.js
  src/Pages/Ootd/Main/Card.js
  src/Pages/Ootd/Main/Card.scss
  src/Pages/Ootd/Main/CardList.js
  src/Pages/Ootd/Main/CardList.scss
  src/Pages/Ootd/Main/Main.js
  src/Pages/Ootd/Main/Main.scss
  src/Pages/Ootd/Main/Modal.js
  src/Pages/Ootd/Main/Modal.scss
  src/Pages/Ootd/Ootd.js
  src/Pages/Ootd/Ootd.scss
Labels: Status: 도움 요청, Status: 리뷰 요청

#27 [14기 엄문주] 로그인 페이지 올립니다.
  src/Component/Login/Login.js
  src/Component/Login/Login.scss
Labels: Status: 리뷰 요청

#28 [14기 박현재] Update: resolve error
  src/Pages/Ootd/Main/Modal.js
  src/Pages/Ootd/Main/Modal.scss
Labels: Status: 리뷰 요청

#26 [14기 장호철] 스타일코드 발표용으로 수정중입니다
  src/Component/CategoryDetail/Component/CategoryJumbotron/CategoryJumbotron.js
  src/Component/CategoryDetail/Component/MdChoice/MdChoice.js
  src/Component/CategoryDetail/Component/MdChoice/Pagination.js
  src/Component/Navbar/NavbarOotd/NavbarOotd.js
  src/Component/Navbar/NavbarOotd/NavbarOotd.scss
  src/Component/Navbar/NavbarStore/NavbarStore.js
  src/Component/ProductDetail/Component/Header/Header.js
  src/Component/ProductDetail/Component/Header/Select/Select.js
  src/Component/Search/Component/User/User.js
  src/Component/Search/Component/User/User.scss
  src/Component/SignUp/SignUp.js
  src/Pages/Ootd/Main/Card.scss
  src/Pages/Ootd/Main/CardList.scss
  src/Pages/Ootd/Main/Main.js
  src/Pages/Ootd/Main/Main.scss
  src/Pages/Ootd/Main/Modal.js
  src/Pages/Ootd/Main/Modal.scss
  src/Pages/Store/Home/Component/PopularProduct/Component/Card.scss
Labels: Status: 추가 기능 구현중
